export const RESTAURANT_DATA = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 1,
    pageIndex: 0,
    scrubber: 0,
    filters: [
      {
        type: "FilterWidget",
        title: "Cuisines",
        key: "CUISINES",
        configType: "checkbox",
        visible: 1,
        options: [
          {
            option: "Afghani",
            selected: 0,
            visible: 1,
          },
          {
            option: "American",
            selected: 0,
            visible: 1,
          },
          {
            option: "Andhra",
            selected: 0,
            visible: 1,
          },
          {
            option: "Arabian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Asian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Awadhi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Bakery",
            selected: 0,
            visible: 1,
          },
          {
            option: "Barbecue",
            selected: 0,
            visible: 1,
          },
          {
            option: "Bengali",
            selected: 0,
            visible: 1,
          },
          {
            option: "Beverages",
            selected: 0,
            visible: 1,
          },
          {
            option: "Bihari",
            selected: 0,
            visible: 1,
          },
          {
            option: "Biryani",
            selected: 0,
            visible: 1,
          },
          {
            option: "Burgers",
            selected: 0,
            visible: 1,
          },
          {
            option: "Burmese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Cafe",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chaat",
            selected: 0,
            visible: 1,
          },
          {
            option: "Chinese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Combo",
            selected: 0,
            visible: 1,
          },
          {
            option: "Continental",
            selected: 0,
            visible: 1,
          },
          {
            option: "Desserts",
            selected: 0,
            visible: 1,
          },
          {
            option: "European",
            selected: 0,
            visible: 1,
          },
          {
            option: "Fast Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Goan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Grill",
            selected: 0,
            visible: 1,
          },
          {
            option: "Gujarati",
            selected: 0,
            visible: 1,
          },
          {
            option: "Healthy Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Home Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Hyderabadi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Ice Cream",
            selected: 0,
            visible: 1,
          },
          {
            option: "Ice Cream Cakes",
            selected: 0,
            visible: 1,
          },
          {
            option: "Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Indonesian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Italian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Italian-American",
            selected: 0,
            visible: 1,
          },
          {
            option: "Japanese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Juices",
            selected: 0,
            visible: 1,
          },
          {
            option: "Kashmiri",
            selected: 0,
            visible: 1,
          },
          {
            option: "Kebabs",
            selected: 0,
            visible: 1,
          },
          {
            option: "Keto",
            selected: 0,
            visible: 1,
          },
          {
            option: "Korean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Lebanese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Lucknowi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Maharashtrian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mangalorean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Meat",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mediterranean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mexican",
            selected: 0,
            visible: 1,
          },
          {
            option: "Mughlai",
            selected: 0,
            visible: 1,
          },
          {
            option: "Navratri Special",
            selected: 0,
            visible: 1,
          },
          {
            option: "Nepalese",
            selected: 0,
            visible: 1,
          },
          {
            option: "North Eastern",
            selected: 0,
            visible: 1,
          },
          {
            option: "North Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Oriental",
            selected: 0,
            visible: 1,
          },
          {
            option: "Paan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pan-Asian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pastas",
            selected: 0,
            visible: 1,
          },
          {
            option: "Pizzas",
            selected: 0,
            visible: 1,
          },
          {
            option: "Popular Brand Store",
            selected: 0,
            visible: 1,
          },
          {
            option: "Portuguese",
            selected: 0,
            visible: 1,
          },
          {
            option: "Punjabi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Rajasthani",
            selected: 0,
            visible: 1,
          },
          {
            option: "Salads",
            selected: 0,
            visible: 1,
          },
          {
            option: "Seafood",
            selected: 0,
            visible: 1,
          },
          {
            option: "Sindhi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Singaporean",
            selected: 0,
            visible: 1,
          },
          {
            option: "Snacks",
            selected: 0,
            visible: 1,
          },
          {
            option: "South Indian",
            selected: 0,
            visible: 1,
          },
          {
            option: "Street Food",
            selected: 0,
            visible: 1,
          },
          {
            option: "Sushi",
            selected: 0,
            visible: 1,
          },
          {
            option: "Sweets",
            selected: 0,
            visible: 1,
          },
          {
            option: "Tandoor",
            selected: 0,
            visible: 1,
          },
          {
            option: "Thai",
            selected: 0,
            visible: 1,
          },
          {
            option: "Thalis",
            selected: 0,
            visible: 1,
          },
          {
            option: "Tibetan",
            selected: 0,
            visible: 1,
          },
          {
            option: "Waffle",
            selected: 0,
            visible: 1,
          },
        ],
        detail: "",
        heading: "Cuisines",
        applicable: 1,
        searchable: 1,
      },
      {
        type: "FilterWidget",
        title: "Show Restaurants With",
        key: "SHOW_RESTAURANTS_WITH",
        configType: "checkbox",
        visible: 1,
        options: [
          {
            option: "Pure Veg",
            selected: 0,
            visible: 1,
          },
        ],
        detail: "",
        heading: "Offers & More",
        applicable: 1,
        searchable: 0,
      },
    ],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
      },
    },
    cards: [
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "topCarousel",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 635529,
                  creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
                  type: "restaurantCollectionV2",
                  link: "49301",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 619141,
                  creativeId: "rng/md/carousel/production/zpkkdkmvlj5cuvqbc50t",
                  type: "restaurantCollectionV2",
                  link: "56413",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607193,
                  creativeId: "rng/md/carousel/production/s5ug2key6e2sptaxku5v",
                  type: "restaurantCollectionV2",
                  link: "56410",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 607195,
                  creativeId: "rng/md/carousel/production/ifi2lbzxeu1hvsqrsip3",
                  type: "restaurantCollectionV2",
                  link: "56421",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  thirdPartyVendor: "",
                  thirdPartyAddress: false,
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "carousel",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "carousel",
          subtype: "openFilter",
          data: {
            cards: [
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181684,
                  creativeId: "bkhjfipzydkoqncrxpyi",
                  type: "restaurantCollectionV2",
                  link: "11718",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Offers Near You",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Offers Near You",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "eyperwsfhaoa5vktjtu4",
                  dwebOpenFilterDeselectIcon: "urw8usdf4mk9aywd59gq",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 273242,
                  creativeId: "rng/md/carousel/production/vquntqrzvkb08pe59cec",
                  type: "restaurantCollectionV2",
                  link: "46147",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Top Picks",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Top Picks",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon:
                    "rng/md/carousel/production/vt13uzhjrg5r49kh9oru",
                  dwebOpenFilterDeselectIcon:
                    "rng/md/carousel/production/ser2sttildk9yt7t2s91",
                },
              },
              {
                type: "carouselElement",
                subtype: "image",
                data: {
                  bannerId: 181680,
                  creativeId: "a3jqjjod5taken7dh1bs",
                  type: "restaurantCollectionV2",
                  link: "11721",
                  cityId: 0,
                  restaurantUuid: "",
                  restaurantParentId: "0",
                  title: "Veg Only",
                  subtitle: "0 OPTIONS",
                  restaurants: [],
                  totalCount: 0,
                  dwebOpenFilterTitle: "Vegetarian Options",
                  dwebOpenFilterBgColor: "#FF0000",
                  dwebOpenFilterSelectIcon: "qtjc8dzfexg72lug37a0",
                  dwebOpenFilterDeselectIcon: "bm8bziikwyvwqsml1clm",
                },
              },
            ],
          },
        },
        parentWidget: false,
      },
      {
        cardType: "seeAllRestaurants",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "seeAllRestaurants",
          data: {
            title: "SEE ALL",
            totalOpenRestaurants: 1481,
            cards: [
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "22490",
                  name: "Pikwik Since 1991",
                  uuid: "50c9f712-3e51-4e61-b974-43d5b68dfa5b",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "poh1opazxy5csaflmftz",
                  cuisines: ["North Indian", "Chinese", "Continental"],
                  tags: [],
                  costForTwo: 60000,
                  costForTwoString: "₹600 FOR TWO",
                  deliveryTime: 33,
                  minDeliveryTime: 33,
                  maxDeliveryTime: 33,
                  slaString: "33 MINS",
                  lastMileTravel: 2,
                  slugs: {
                    restaurant: "pikwik-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address: "409, 4th Floor, Ring Road Mall, Rohini, New Delhi",
                  locality: "Rohini",
                  parentId: 7462,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7460303~p=1~eid=00000189-544a-8373-086f-280200a1016e~srvts=1689336316787",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "22490",
                    deliveryTime: 33,
                    minDeliveryTime: 33,
                    maxDeliveryTime: 33,
                    lastMileTravel: 2,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.1",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "254192",
                  name: "McDonald's",
                  uuid: "84f736b1-0f83-460b-95c0-931d275fa63b",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "08eee882fda81b68e5c36e3a5d89d8c0",
                  cuisines: ["American"],
                  tags: [],
                  costForTwo: 40000,
                  costForTwoString: "₹400 FOR TWO",
                  deliveryTime: 31,
                  minDeliveryTime: 31,
                  maxDeliveryTime: 31,
                  slaString: "31 MINS",
                  lastMileTravel: 2,
                  slugs: {
                    restaurant: "mcdonalds-delhi-d-mall-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "Delhi D-Mall Rohini, Plot No. 1B5, Twin District Center. D-Mall , Sector-10, Rohini,New Delhi- 110085",
                  locality: "Sector 10",
                  parentId: 630,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "FREE ITEM",
                    subHeader: "",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "254192",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    lastMileTravel: 2,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "36900",
                  name: "Wah Bhai Wah",
                  uuid: "7ebbf893-5282-4cd2-8599-0b96126e6c83",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "ach30rz8ebyckifblioq",
                  cuisines: ["North Indian", "Chinese", "Tandoor", "Beverages"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  slaString: "21 MINS",
                  lastMileTravel: 0.4000000059604645,
                  slugs: {
                    restaurant: "wah-bhai-wah-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address: "A 1/168 & 169, Sector 4, Rohini, New Delhi",
                  locality: "Sector 4",
                  parentId: 14882,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.4 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "36900",
                    deliveryTime: 21,
                    minDeliveryTime: 21,
                    maxDeliveryTime: 21,
                    lastMileTravel: 0.4000000059604645,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.6",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "347493",
                  name: "Hudson Chopsticks",
                  uuid: "0f7f7911-d443-458a-8a23-eb4507dff840",
                  city: "4",
                  area: "Prashant Vihar",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "sphijl0wioxo55xxdinz",
                  cuisines: [
                    "Chinese",
                    "Thai",
                    "Pan-Asian",
                    "Snacks",
                    "Tibetan",
                    "Nepalese",
                    "Asian",
                    "Seafood",
                    "Beverages",
                    "Desserts",
                    "Barbecue",
                    "Grill",
                    "Fast Food",
                  ],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 31,
                  minDeliveryTime: 31,
                  maxDeliveryTime: 31,
                  slaString: "31 MINS",
                  lastMileTravel: 3.5,
                  slugs: {
                    restaurant: "hudson-chopsticks-rohini-rohini-2",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    " Shop No. 4, Ground Floor, Block C-9/62, Sector 8C, Rohini, Delhi, 110085, India.. Landmark : Bhagwan Mahavir Marg opposite Saroj Hospital",
                  locality: "Bhagwan Mahavir Marg",
                  parentId: 7129,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3700,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3700,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3700",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7489540~p=4~eid=00000189-544a-8373-086f-280300a1046a~srvts=1689336316787",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3.5 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "347493",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    lastMileTravel: 3.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.1",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "389326",
                  name: "Bittoo Samosay Wala",
                  uuid: "b784d46d-78f4-4169-a7e9-6a57527a629f",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "aawlxgtno7oq9qfylkrf",
                  cuisines: ["Snacks", "Chinese", "Chaat"],
                  tags: [],
                  costForTwo: 19900,
                  costForTwoString: "₹199 FOR TWO",
                  deliveryTime: 14,
                  minDeliveryTime: 14,
                  maxDeliveryTime: 14,
                  slaString: "14 MINS",
                  lastMileTravel: 0.20000000298023224,
                  slugs: {
                    restaurant: "bittoo-samosay-wala-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "Shop no. - E19/312, Rohini sec- 3, New Delhi-110085",
                  locality: "Sector 3",
                  parentId: 242406,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "389326",
                    deliveryTime: 14,
                    minDeliveryTime: 14,
                    maxDeliveryTime: 14,
                    lastMileTravel: 0.20000000298023224,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.8",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "10208",
                  name: "Burger King",
                  uuid: "cff4922d-5630-4712-b902-b59427f5d9e6",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
                  cuisines: ["Burgers", "American"],
                  tags: [],
                  costForTwo: 35000,
                  costForTwoString: "₹350 FOR TWO",
                  deliveryTime: 29,
                  minDeliveryTime: 29,
                  maxDeliveryTime: 29,
                  slaString: "29 MINS",
                  lastMileTravel: 2.0999999046325684,
                  slugs: {
                    restaurant:
                      "burger-king-d-mall-twin-district-center-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "Unit 21-24, Ground Floor, D Mall, Twin District Center, Rohini, New Delhi",
                  locality: "Sector 10",
                  parentId: 166,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "EVERY ITEM",
                    subHeader: "@ ₹129",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "10208",
                    deliveryTime: 29,
                    minDeliveryTime: 29,
                    maxDeliveryTime: 29,
                    lastMileTravel: 2.0999999046325684,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "444780",
                  name: "Theobroma",
                  uuid: "b7658b7e-bcb9-4fc5-9439-f0b88c7f1ff2",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "egg7tpiijieiows8e6xj",
                  cuisines: ["Bakery", "Desserts"],
                  tags: [],
                  costForTwo: 85000,
                  costForTwoString: "₹850 FOR TWO",
                  deliveryTime: 21,
                  minDeliveryTime: 21,
                  maxDeliveryTime: 21,
                  slaString: "21 MINS",
                  lastMileTravel: 2.200000047683716,
                  slugs: {
                    restaurant: "theobroma-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "Shop No. 29, Plot No.15, NN Mall, Mangalam Place,Sector-3,Rohini,New Delhi-110085",
                  locality: "Sector 3",
                  parentId: 1040,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7262140~p=13~eid=00000189-544a-8373-086f-280600a10d25~srvts=1689336316787",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2.2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "444780",
                    deliveryTime: 21,
                    minDeliveryTime: 21,
                    maxDeliveryTime: 21,
                    lastMileTravel: 2.200000047683716,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.5",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "509687",
                  name: "Baozi Momos",
                  uuid: "9684d6ea-d641-4366-95c4-2e9ea750cf78",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "100+ ratings",
                  cloudinaryImageId: "wrn7d4fcudhxmj28njho",
                  cuisines: ["Chinese", "Snacks"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 28,
                  minDeliveryTime: 28,
                  maxDeliveryTime: 28,
                  slaString: "28 MINS",
                  lastMileTravel: 1.100000023841858,
                  slugs: {
                    restaurant: "baozi-momos-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "72, Sector 3, Pocket 34, Sector 3H, Rohini, Delhi, 110085, India",
                  locality: "Sector 3",
                  parentId: 41667,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "1.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "509687",
                    deliveryTime: 28,
                    minDeliveryTime: 28,
                    maxDeliveryTime: 28,
                    lastMileTravel: 1.100000023841858,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.3",
                  totalRatings: 100,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "341033",
                  name: "Bakingo",
                  uuid: "48e87729-9a78-405d-b021-af7e46b2ccd7",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "1000+ ratings",
                  cloudinaryImageId: "rmnzl74nmlldrsv9bnvk",
                  cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 27,
                  minDeliveryTime: 27,
                  maxDeliveryTime: 27,
                  slaString: "27 MINS",
                  lastMileTravel: 3,
                  slugs: {
                    restaurant: "bakingo-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "Shop No 4 on Ground Floor A  part of built up property no 1143 village rithala near bagga service centre delhi 110085 North West  Delhi 110085",
                  locality: "Rithala",
                  parentId: 3818,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  ribbon: [
                    {
                      type: "PROMOTED",
                    },
                  ],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3700,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3700,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3700",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID:
                    "cid=7354707~p=19~eid=00000189-544a-8373-086f-280800a11324~srvts=1689336316787",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "341033",
                    deliveryTime: 27,
                    minDeliveryTime: 27,
                    maxDeliveryTime: 27,
                    lastMileTravel: 3,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: true,
                  avgRating: "4.3",
                  totalRatings: 1000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "517109",
                  name: "Wah Bhai Wah 2 The Vaishno Rasoi",
                  uuid: "a93786fa-034f-4418-95ca-e3f87cfc1eb6",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "pdkdux94trmdm8teflio",
                  cuisines: ["North Indian", "Indian", "Snacks"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 25,
                  minDeliveryTime: 25,
                  maxDeliveryTime: 25,
                  slaString: "25 MINS",
                  lastMileTravel: 0.6000000238418579,
                  slugs: {
                    restaurant:
                      "wah-bhai-wah-2-the-vaishno-rasoi-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "139 GROUND FLOOR, BLK-B, VIJAY VIHAR, ROHINI PH-2, Rohini, North West , , Delhi, 110085",
                  locality: "2Nd Phase",
                  parentId: 309094,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.6 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "50% OFF",
                    subHeader: "UPTO ₹100",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "517109",
                    deliveryTime: 25,
                    minDeliveryTime: 25,
                    maxDeliveryTime: 25,
                    lastMileTravel: 0.6000000238418579,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "2.9",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "16866",
                  name: "Pizza Hut",
                  uuid: "4743f700-6904-4382-a495-2df8f81f3570",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
                  cuisines: ["Pizzas"],
                  tags: [],
                  costForTwo: 35000,
                  costForTwoString: "₹350 FOR TWO",
                  deliveryTime: 29,
                  minDeliveryTime: 29,
                  maxDeliveryTime: 29,
                  slaString: "29 MINS",
                  lastMileTravel: 2,
                  slugs: {
                    restaurant: "pizza-hut-aggarwal-city-plaza-13-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "17, Mangalam Place, Aggarwal City Plaza, Sector 3, Rohini",
                  locality: "Sector 3",
                  parentId: 721,
                  unserviceable: false,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "60% OFF",
                    subHeader: "UPTO ₹120",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "16866",
                    deliveryTime: 29,
                    minDeliveryTime: 29,
                    maxDeliveryTime: 29,
                    lastMileTravel: 2,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.6",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "44058",
                  name: "Wah Ji Wah",
                  uuid: "9b3849fd-6481-4089-84ea-a769fb9753b4",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "1ebb03f7ddc11fa416ac040de11fcf6c",
                  cuisines: ["North Indian", "Chinese", "Snacks"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 41,
                  minDeliveryTime: 41,
                  maxDeliveryTime: 41,
                  slaString: "41 MINS",
                  lastMileTravel: 2.200000047683716,
                  slugs: {
                    restaurant: "wah-ji-wah-rohini-rohini-3",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "A1/36 surya market, Budhvihar, phase -1,Main kanjhawala road , near anubhav Vatika",
                  locality: "1st Phase",
                  parentId: 966,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "LIGHT",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "2.2 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "₹125 OFF",
                    subHeader: "ABOVE ₹249",
                    discountTag: "FLAT DEAL",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "44058",
                    deliveryTime: 41,
                    minDeliveryTime: 41,
                    maxDeliveryTime: 41,
                    lastMileTravel: 2.200000047683716,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "LIGHT",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.9",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "365223",
                  name: "Samosa Fusion",
                  uuid: "1b649ce0-c312-4a09-81dd-847bd277c7d5",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "cryv5c0c5mwn8fnmy35y",
                  cuisines: ["Snacks", "Pizzas", "Burgers"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 39,
                  minDeliveryTime: 39,
                  maxDeliveryTime: 39,
                  slaString: "39 MINS",
                  lastMileTravel: 0.800000011920929,
                  slugs: {
                    restaurant: "samosa-fusion-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "HOUSE NO. 60, BLOCK - B, PKT 9, SEC 3, LANDMARK NEAR MOTHER DAIRY BOTH, ROHINI, NEW DELHI, ROHINI, NORTH WEST (DELHI) - 110085",
                  locality: "SEC 3",
                  parentId: 176544,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.8 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "365223",
                    deliveryTime: 39,
                    minDeliveryTime: 39,
                    maxDeliveryTime: 39,
                    lastMileTravel: 0.800000011920929,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.1",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "472509",
                  name: "Alex Pizza Pasta Point",
                  uuid: "3972af6b-46b7-46d4-93a3-5d43e74f3ce1",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "nrmdncoiyxwnidi8uiub",
                  cuisines: ["Italian", "Chinese", "Fast Food"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 30,
                  minDeliveryTime: 30,
                  maxDeliveryTime: 30,
                  slaString: "30 MINS",
                  lastMileTravel: 0.20000000298023224,
                  slugs: {
                    restaurant: "alex-pizza-pasta-point-rohini-rohini",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "A1-240, Pocket A-1, Pocket 1, Sector 4, Rohini, Delhi, 110085, India",
                  locality: "Sector 4",
                  parentId: 283729,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.2 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "472509",
                    deliveryTime: 30,
                    minDeliveryTime: 30,
                    maxDeliveryTime: 30,
                    lastMileTravel: 0.20000000298023224,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "432396",
                  name: "Bansi Wala",
                  uuid: "c30edeca-94a2-4086-9424-1e007a2c39ec",
                  city: "4",
                  area: "Rohini",
                  totalRatingsString: "500+ ratings",
                  cloudinaryImageId: "xghsu7ngyzloge1eifii",
                  cuisines: ["North Indian", "Snacks", "Chinese", "Bakery"],
                  tags: [],
                  costForTwo: 30000,
                  costForTwoString: "₹300 FOR TWO",
                  deliveryTime: 17,
                  minDeliveryTime: 17,
                  maxDeliveryTime: 17,
                  slaString: "17 MINS",
                  lastMileTravel: 0.800000011920929,
                  slugs: {
                    restaurant: "bansiwala-rohini-rohini-4",
                    city: "delhi",
                  },
                  cityState: "4",
                  address:
                    "58, Ground Floor, Bhock-H, Pocket-33, Sector-3, Rohini, Delhi-110085",
                  locality: "Sector 3",
                  parentId: 6840,
                  unserviceable: false,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      {
                        name: "distance",
                        fee: 3100,
                        message: "",
                      },
                      {
                        name: "time",
                        fee: 0,
                        message: "",
                      },
                      {
                        name: "special",
                        fee: 0,
                        message: "",
                      },
                    ],
                    totalFees: 3100,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3100",
                    icon: "",
                  },
                  availability: {
                    opened: true,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "0.8 kms",
                  hasSurge: false,
                  aggregatedDiscountInfoV3: {
                    header: "10% OFF",
                    subHeader: "UPTO ₹40",
                    discountTag: "",
                    headerTypeV2: 0,
                  },
                  sla: {
                    restaurantId: "432396",
                    deliveryTime: 17,
                    minDeliveryTime: 17,
                    maxDeliveryTime: 17,
                    lastMileTravel: 0.800000011920929,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.0",
                  totalRatings: 500,
                  new: false,
                },
                subtype: "basic",
              },
            ],
            totalRestaurants: 1481,
          },
          subtype: "personalized",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "830d9fea-e125-4939-860c-85341811ff2c",
  sid: "86hd3491-cfd1-441e-813c-8ff0b0c64f96",
  deviceId: "1f596642-de30-dc12-e2b1-843f0d4e890b",
  csrfToken: "e5cwPgQTwMjK-1lqDWeWzVtEOdXNkJ37MFidq4I4",
};
